name: Check Changeset

on:
    pull_request:
        branches:
            - develop
        paths-ignore:
            - "docs/**"
            - "**/*.md"
            - ".vscode/**"
            - ".github/workflows/**"

jobs:
    validate-changeset:
        name: Verify Changelog File
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Código
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.BOT_GITHUB_TOKEN }}

            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Instalar Dependências
              run: npm install

            - name: Validar existência de Changeset

              run: npx changeset status --since=origin/develop
